### ISSUE TITLE
CMS setup

### ISSUE THREAD

**Issue by jillesmc** [madeiramadeirabr/template-react-nextjs#2]
Create example project inside Dato dashboard.
Create some example models for hello word and set up configuration inside nextjs app.

**Comment by jillesmc** [comment]
Criei um projeto no DatoCMS para este projeto, entretanto não sei se vamos manter, pois na conta da MadeiraMadeira temos direito a apenas 3 projetos.
Por hora usemos este https://template-nexjs.admin.datocms.com/

**Comment by accezar** [comment]
É o suficiente pra exemplificar o conteudo das paginas estáticas, criei dois models (`home` e `about`) e tb um bloco `hero` que ja serve pra demonstrar a integração. Outros tipos de integrações para outras páginas vai depender do requisito.
